// HWSB STARTING CODE (you can remove if u are making ur own shit)
function showNotification(){new Notification("HWSB Notification",{body:"[HWSB]: Injected into discord, open with INS"})}function checkElement(e){return new Promise((t,n)=>{let o=setInterval(()=>{let n=document.querySelector(e);n&&(clearInterval(o),t(n))},500)})}console.log("[HWSB]: Injected into discord, open with INS"),"Notification"in window?"granted"===Notification.permission?showNotification():"denied"!==Notification.permission&&Notification.requestPermission().then(function(e){"granted"===e&&showNotification()}):console.log("Error: Notifications not supported in this browser."),checkElement('div[class^="content_"]').then(e=>{console.log('The div with class starting with "content_" exists.');let t=e.querySelector("video");if(t){t.remove(),console.log("Video removed.");let n=document.createElement("img");n.src="https://imgs.search.brave.com/KYbOwGcq-hLuBmakF5WYcGSHcbkDtaJCVXVABONq66w/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZmF2cG5nLmNvbS8x/Mi8yNS8xNS9hc3Rv/bGZvLWRpc2NvcmQt/ZmF0ZS1ncmFuZC1v/cmRlci1lbW9qaS1y/ZXNldGVyYS1wbmct/ZmF2cG5nLTJLdHlL/VGhHUjlNeVVNUU5k/V3BVNENUaHBfdC5q/cGc",n.style.width="100px",n.style.height="100px",n.style.marginBottom="50px",n.style.animation="spin 2s linear infinite, glow 1s ease-in-out infinite alternate",n.style.border="3px solid pink",n.style.boxShadow="0 0 10px pink",n.style.borderRadius="50%";let o=document.createElement("style");o.textContent=`
            @keyframes spin {
                from { transform: rotate(0deg); }
                to { transform: rotate(360deg); }
            }
        `,document.head.appendChild(o);let i=document.createElement("style");i.textContent=`
            @keyframes glow {
                from { box-shadow: 0 0 10px pink; }
                to { box-shadow: 0 0 20px pink, 0 0 30px pink; }
            }
        `,document.head.appendChild(i),e.insertBefore(n,e.firstChild),console.log("Image inserted above the text.")}else console.log("No video found.")}).catch(()=>{console.log('The div with class starting with "content_" does not exist.')}),checkElement('div[class^="info__755e1"]').then(e=>{let t=e.querySelector("span");if(t){let n=t.cloneNode(!0);n.textContent="HWSB V1 (femboy edition)",e.appendChild(n),console.log("Cloned span added to the info div.")}else console.log("No span found to clone.")}).catch(()=>{console.log('The div with class starting with "info" does not exist.')}),checkElement('div[class^="tip_"]').then(e=>{e.textContent="HWSB V1 (femboy edition)"}).catch(()=>{console.log('The div with class starting with "tip_" does not exist.')}),checkElement('div[id="app-mount"]').then(e=>{let t=document.createElement("div"),n=document.createElement("div"),o=document.createElement("div");t.style.width="100%",t.style.height="100%",t.style.background="rgba(0, 0, 0, 0.5)",t.style.position="fixed",t.style.top="0",t.style.left="0",t.style.display="none",t.style.zIndex="9999",n.style.width="300px",n.style.height="50px",n.style.background="#414141",n.style.position="absolute",n.style.top="20px",n.style.left="50%",n.style.transform="translateX(-50%)",n.style.boxShadow="0 0 10px pink",n.style.borderRadius="25px",n.style.color="#fff",n.style.display="flex",n.style.justifyContent="center",n.style.alignItems="center",checkElement(".info__40462.userTag__28f9c span").then(e=>{let t=e.textContent;n.textContent="Welcome back, "+t}).catch(()=>{console.log("The span with the username does not exist.")}),o.style.width="500px",o.style.height="250px",o.style.background="#414141",o.style.position="absolute",o.style.top="100px",o.style.left="50%",o.style.transform="translateX(-50%)",o.style.borderRadius="10px",o.style.boxShadow="0 0 10px pink",document.addEventListener("keydown",function(e){"Insert"===e.key&&(t.style.display="none"===t.style.display?"block":"none","none"===t.style.display&&(o.style.top="100px",o.style.left="50%"))});let i=0,s=0,l=0,a=0;function c(e){(e=e||window.event).preventDefault(),i=l-e.clientX,s=a-e.clientY,l=e.clientX,a=e.clientY,o.style.top=o.offsetTop-s+"px",o.style.left=o.offsetLeft-i+"px"}function d(){document.onmouseup=null,document.onmousemove=null}o.onmousedown=function(e){(e=e||window.event).preventDefault(),l=e.clientX,a=e.clientY,document.onmouseup=d,document.onmousemove=c},t.appendChild(n),t.appendChild(o),e.appendChild(t)});